buscacep/address/urls.py
from django.urls import path, include
# from .views import AddressCreateView
# from .forms import AddressCreateForm
from . import views

urlpatterns = [
    path('list', views.home, name='address-home'),
    # path('register/', AddressCreateView.as_view(),  name='address-register'),
    # path('register/', views.register,  name='address-register'),
    path('', views.AddressFormView.as_view(),  name='address-register'),
    path('create/', views.create, name='address-create'),
]

buscacep/buscacep/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('address.urls')),
]

buscacep/address/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Address(models.Model):
    cep = models.CharField(max_length=9, primary_key=True)
    street = models.CharField(max_length=100)
    number = models.CharField(max_length=10)
    neighborhood = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    uf = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    complement = models.CharField(max_length=100, blank=True)


    def __str__(self):
        return f'{self.cep} - {self.street}'

    def get_absolute_url(self):
        return reverse('address-home')

buscacep/address/forms.py
from django import forms
from .models import Address

class AddressForm(forms.Form):
    cep = forms.CharField(label='CEP', max_length=9)
    street = forms.CharField(label='Rua', max_length=100)
    number = forms.CharField(label='Número', max_length=10)
    neighborhood = forms.CharField(label='Bairro', max_length=100)
    city = forms.CharField(label='Cidade', max_length=100)
    uf = forms.CharField(label='UF', max_length=100)
    description = forms.CharField(label='Descricão', required=False)
    complement = forms.CharField(label='Complemento', max_length=100, required=False)

    # class Meta:
    #     model = Address
    #     template_name = 'address/register.html'
    #     fields = [
    #         'cep',
    #         'street',
    #         'number',
    #         'neighborhood',
    #         'city',
    #         'uf',
    #         'description',
    #         'complement'
    #     ]

buscacep/address/views.py
from django.shortcuts import render, redirect
from .models import Address
from django.urls import reverse_lazy

from django.views.generic import FormView
from .forms import AddressForm


def home(request):
    context = {
        'addresses': Address.objects.all(),
    }
    return render(request, 'address/home.html', context)


def create(request):
    if request.method == "POST":
        form = AddressForm(request.POST)
        if form.is_valid():
            if not Address.objects.filter(cep=form.cleaned_data['cep']):
                a = Address.objects.create(
                    cep = form.cleaned_data['cep'],
                    street = form.cleaned_data['street'],
                    number = form.cleaned_data['number'],
                    neighborhood = form.cleaned_data['neighborhood'],
                    city = form.cleaned_data['city'],
                    uf = form.cleaned_data['uf'],
                    description = form.cleaned_data['description'],
                    complement = form.cleaned_data['complement']
                )
            else:
                Address.objects.filter(cep=form.cleaned_data['cep']).update(
                    street = form.cleaned_data['street'],
                    number = form.cleaned_data['number'],
                    neighborhood = form.cleaned_data['neighborhood'],
                    city = form.cleaned_data['city'],
                    uf = form.cleaned_data['uf'],
                    description = form.cleaned_data['description'],
                    complement = form.cleaned_data['complement']
                )
            return redirect('address-home')
    else:
        form = AddressForm()
    return render(request, 'address/register.html', {'form': form})


class AddressFormView(FormView):
    form_class = AddressForm
    success_url = reverse_lazy('address-home')
    template_name = 'address/register.html'

buscacep/address/templates/address/address_form.html
{% extends "address/base.html" %}

{% block content %}
<div class="content-section">
    <form method="post" >
        {% csrf_token %}

        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Cadastro de endereço</legend>
            {{ form.as_p }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-dark" type="submit">Cadastrar</button>
        </div>
    </form>
    {% block other_scripts %}
      <script type="text/javascript">
        $(document).ready(function() {
          console.log("carregado");

          $("#id_cep").blur(function() {
            let cep = $('#id_cep').val().replace(/\D/g, '');
            console.log(cep);

            fetch(`https://viacep.com.br/ws/${cep}/json/`).then(function(response) {
              return response.json();
            }).then(function(data) {
              $("#id_street").val(data.logradouro);
              $("#id_neighborhood").val(data.bairro);
              $("#id_city").val(data.localidade);
              $("#id_uf").val(data.uf);
              $("#id_complemento").val(data.complemento);
            }).catch(function(err) {
              $("#id_street").val("");
              $("#id_neighborhood").val("");
              $("#id_city").val("");
              $("#id_uf").val("");
              $("#id_complemento").val("");
              console.log('Erro: ' + err.message);
            });
          });
        });
      </script>
    {% endblock other_scripts %}
</div>
{% endblock content %}

buscacep/address/templates/address/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script> -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'address/main.css' %}">

    <title>BuscaCep
      {% if title %}
         - {{title}}
      {% endif %}
    </title>

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="{% url 'address-home' %}">BuscaCep</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'address-home' %}">Listar endereços</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'address-register' %}">Cadastrar um endereço</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <main role="main" class="container">
      <h1></h1>
      {% block content %}{% endblock content %}
    </main>

    {% block other_scripts %}{% endblock other_scripts %}
  </body>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</html>

buscacep/address/templates/address/home.html
{% extends "address/base.html" %}

{% block content %}
  <h1>Listagem de endereços</h1>

  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th scope="col"> Cep</th>
        <th scope="col"> Endereço</th>
        <th scope="col"> Número</th>
        <th scope="col"> Complemento</th>
        <th scope="col"> Bairro</th>
        <th scope="col"> Cidade</th>
        <th scope="col"> Uf</th>
        <th scope="col"> Descricão</th>
      </tr>
    </thead>
    <tbody>
      {% for address in addresses %}
      <tr>
        <th scope="row"> {{ address.cep }}</th>
        <td>{{ address.street }}</td>
        <td>{{ address.number }}</td>
        <td>{{ address.complement }}</td>
        <td>{{ address.neighborhood }}</td>
        <td>{{ address.city }}</td>
        <td>{{ address.uf }}</td>
        <td>{{ address.description }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}

buscacep/address/templates/address/register.html
{% extends "address/base.html" %}

{% block content %}
<div class="content-section">
    <form method="post" action="{% url 'address-create' %}">
        {% csrf_token %}

        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Cadastro de endereço</legend>
            {{ form.cep.errors }}
            {{ form.as_p }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-dark" type="submit">Cadastrar</button>
        </div>
    </form>
    {% block other_scripts %}
      <script type="text/javascript">
        $(document).ready(function() {
          console.log("carregado");

          $("#id_cep").blur(function() {
            let cep = $('#id_cep').val().replace(/\D/g, '');
            console.log(cep);

            fetch(`https://viacep.com.br/ws/${cep}/json/`).then(function(response) {
              return response.json();
            }).then(function(data) {
              $("#id_street").val(data.logradouro);
              $("#id_neighborhood").val(data.bairro);
              $("#id_city").val(data.localidade);
              $("#id_uf").val(data.uf);
              $("#id_complemento").val(data.complemento);
            }).catch(function(err) {
              $("#id_street").val("");
              $("#id_neighborhood").val("");
              $("#id_city").val("");
              $("#id_uf").val("");
              $("#id_complemento").val("");
              console.log('Error: ' + err.message);
            });
          });
        });
      </script>
    {% endblock other_scripts %}
</div>
{% endblock content %}

buscacep/address/templates/address/snippets.html
<article class="media content-section">
  <div class="media-body">
    <div class="article-metadata">
      <p class="mr-2">Hello</p>
      <small class="text-muted">Hello</small>
    </div>
    <h2 class="article-title">Hello</h2>
    <p class="article-content">Hello</p>
  </div>
</article>